// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1113595894;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'engine',
        ioDirectory: '../engine/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  double crateApiEngineApiEngineSampleRate();

  Future<void> crateApiEngineApiInitApp();

  bool crateApiEngineApiIsRunning();

  Future<LoadedClip> crateApiEngineApiLoadWav({
    required int track,
    required String path,
  });

  int crateApiEngineApiMaxTracks();

  Stream<MixerMeters> crateApiEngineApiMeterStream();

  void crateApiEngineApiPause();

  void crateApiEngineApiPlay();

  Stream<PlaybackStatus> crateApiEngineApiPlaybackStatusStream();

  Stream<Float32List> crateApiEngineApiScopeStream();

  void crateApiEngineApiSeek({required double secs});

  void crateApiEngineApiSetLooping({required bool looping});

  void crateApiEngineApiSetMasterGainDb({required double db});

  void crateApiEngineApiSetMasterGainLinear({required double linear});

  void crateApiEngineApiSetMasterPan({required double pan});

  void crateApiEngineApiSetTrackEqBandEnabled({
    required int track,
    required int band,
    required bool on_,
  });

  void crateApiEngineApiSetTrackEqBandFreq({
    required int track,
    required int band,
    required double hz,
  });

  void crateApiEngineApiSetTrackEqBandGainDb({
    required int track,
    required int band,
    required double db,
  });

  void crateApiEngineApiSetTrackEqBandKind({
    required int track,
    required int band,
    required int kind,
  });

  void crateApiEngineApiSetTrackEqBandQ({
    required int track,
    required int band,
    required double q,
  });

  void crateApiEngineApiSetTrackGainDb({
    required int track,
    required double db,
  });

  void crateApiEngineApiSetTrackGainLinear({
    required int track,
    required double linear,
  });

  void crateApiEngineApiSetTrackPan({required int track, required double pan});

  void crateApiEngineApiStop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  double crateApiEngineApiEngineSampleRate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineSampleRateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineSampleRateConstMeta =>
      const TaskConstMeta(debugName: "engine_sample_rate", argNames: []);

  @override
  Future<void> crateApiEngineApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiEngineApiIsRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiIsRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiIsRunningConstMeta =>
      const TaskConstMeta(debugName: "is_running", argNames: []);

  @override
  Future<LoadedClip> crateApiEngineApiLoadWav({
    required int track,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_loaded_clip,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineApiLoadWavConstMeta,
        argValues: [track, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiLoadWavConstMeta =>
      const TaskConstMeta(debugName: "load_wav", argNames: ["track", "path"]);

  @override
  int crateApiEngineApiMaxTracks() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiMaxTracksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiMaxTracksConstMeta =>
      const TaskConstMeta(debugName: "max_tracks", argNames: []);

  @override
  Stream<MixerMeters> crateApiEngineApiMeterStream() {
    final sink = RustStreamSink<MixerMeters>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_mixer_meters_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiEngineApiMeterStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineApiMeterStreamConstMeta =>
      const TaskConstMeta(debugName: "meter_stream", argNames: ["sink"]);

  @override
  void crateApiEngineApiPause() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiPauseConstMeta =>
      const TaskConstMeta(debugName: "pause", argNames: []);

  @override
  void crateApiEngineApiPlay() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiPlayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiPlayConstMeta =>
      const TaskConstMeta(debugName: "play", argNames: []);

  @override
  Stream<PlaybackStatus> crateApiEngineApiPlaybackStatusStream() {
    final sink = RustStreamSink<PlaybackStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_playback_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiEngineApiPlaybackStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineApiPlaybackStatusStreamConstMeta =>
      const TaskConstMeta(
        debugName: "playback_status_stream",
        argNames: ["sink"],
      );

  @override
  Stream<Float32List> crateApiEngineApiScopeStream() {
    final sink = RustStreamSink<Float32List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiEngineApiScopeStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineApiScopeStreamConstMeta =>
      const TaskConstMeta(debugName: "scope_stream", argNames: ["sink"]);

  @override
  void crateApiEngineApiSeek({required double secs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(secs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSeekConstMeta,
        argValues: [secs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSeekConstMeta =>
      const TaskConstMeta(debugName: "seek", argNames: ["secs"]);

  @override
  void crateApiEngineApiSetLooping({required bool looping}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(looping, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetLoopingConstMeta,
        argValues: [looping],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetLoopingConstMeta =>
      const TaskConstMeta(debugName: "set_looping", argNames: ["looping"]);

  @override
  void crateApiEngineApiSetMasterGainDb({required double db}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(db, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetMasterGainDbConstMeta,
        argValues: [db],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetMasterGainDbConstMeta =>
      const TaskConstMeta(debugName: "set_master_gain_db", argNames: ["db"]);

  @override
  void crateApiEngineApiSetMasterGainLinear({required double linear}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(linear, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetMasterGainLinearConstMeta,
        argValues: [linear],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetMasterGainLinearConstMeta =>
      const TaskConstMeta(
        debugName: "set_master_gain_linear",
        argNames: ["linear"],
      );

  @override
  void crateApiEngineApiSetMasterPan({required double pan}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(pan, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetMasterPanConstMeta,
        argValues: [pan],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetMasterPanConstMeta =>
      const TaskConstMeta(debugName: "set_master_pan", argNames: ["pan"]);

  @override
  void crateApiEngineApiSetTrackEqBandEnabled({
    required int track,
    required int band,
    required bool on_,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_u_32(band, serializer);
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackEqBandEnabledConstMeta,
        argValues: [track, band, on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackEqBandEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_eq_band_enabled",
        argNames: ["track", "band", "on_"],
      );

  @override
  void crateApiEngineApiSetTrackEqBandFreq({
    required int track,
    required int band,
    required double hz,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_u_32(band, serializer);
          sse_encode_f_32(hz, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackEqBandFreqConstMeta,
        argValues: [track, band, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackEqBandFreqConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_eq_band_freq",
        argNames: ["track", "band", "hz"],
      );

  @override
  void crateApiEngineApiSetTrackEqBandGainDb({
    required int track,
    required int band,
    required double db,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_u_32(band, serializer);
          sse_encode_f_32(db, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackEqBandGainDbConstMeta,
        argValues: [track, band, db],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackEqBandGainDbConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_eq_band_gain_db",
        argNames: ["track", "band", "db"],
      );

  @override
  void crateApiEngineApiSetTrackEqBandKind({
    required int track,
    required int band,
    required int kind,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_u_32(band, serializer);
          sse_encode_u_32(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackEqBandKindConstMeta,
        argValues: [track, band, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackEqBandKindConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_eq_band_kind",
        argNames: ["track", "band", "kind"],
      );

  @override
  void crateApiEngineApiSetTrackEqBandQ({
    required int track,
    required int band,
    required double q,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_u_32(band, serializer);
          sse_encode_f_32(q, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackEqBandQConstMeta,
        argValues: [track, band, q],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackEqBandQConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_eq_band_q",
        argNames: ["track", "band", "q"],
      );

  @override
  void crateApiEngineApiSetTrackGainDb({
    required int track,
    required double db,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_f_32(db, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackGainDbConstMeta,
        argValues: [track, db],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackGainDbConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_gain_db",
        argNames: ["track", "db"],
      );

  @override
  void crateApiEngineApiSetTrackGainLinear({
    required int track,
    required double linear,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_f_32(linear, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackGainLinearConstMeta,
        argValues: [track, linear],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackGainLinearConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_gain_linear",
        argNames: ["track", "linear"],
      );

  @override
  void crateApiEngineApiSetTrackPan({required int track, required double pan}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(track, serializer);
          sse_encode_f_32(pan, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiSetTrackPanConstMeta,
        argValues: [track, pan],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiSetTrackPanConstMeta =>
      const TaskConstMeta(
        debugName: "set_track_pan",
        argNames: ["track", "pan"],
      );

  @override
  void crateApiEngineApiStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiStopConstMeta =>
      const TaskConstMeta(debugName: "stop", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MixerMeters> dco_decode_StreamSink_mixer_meters_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PlaybackStatus> dco_decode_StreamSink_playback_status_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LoadedClip dco_decode_loaded_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return LoadedClip(
      sampleRate: dco_decode_f_32(arr[0]),
      channels: dco_decode_u_32(arr[1]),
      frames: dco_decode_u_64(arr[2]),
      durationSecs: dco_decode_f_64(arr[3]),
      waveformMin: dco_decode_list_prim_f_32_strict(arr[4]),
      waveformMax: dco_decode_list_prim_f_32_strict(arr[5]),
    );
  }

  @protected
  MixerMeters dco_decode_mixer_meters(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MixerMeters(
      trackPeaksL: dco_decode_list_prim_f_32_strict(arr[0]),
      trackPeaksR: dco_decode_list_prim_f_32_strict(arr[1]),
      masterPeakL: dco_decode_f_32(arr[2]),
      masterPeakR: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  PlaybackStatus dco_decode_playback_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlaybackStatus(
      positionSecs: dco_decode_f_64(arr[0]),
      playing: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MixerMeters> sse_decode_StreamSink_mixer_meters_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PlaybackStatus> sse_decode_StreamSink_playback_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LoadedClip sse_decode_loaded_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sampleRate = sse_decode_f_32(deserializer);
    var var_channels = sse_decode_u_32(deserializer);
    var var_frames = sse_decode_u_64(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    var var_waveformMin = sse_decode_list_prim_f_32_strict(deserializer);
    var var_waveformMax = sse_decode_list_prim_f_32_strict(deserializer);
    return LoadedClip(
      sampleRate: var_sampleRate,
      channels: var_channels,
      frames: var_frames,
      durationSecs: var_durationSecs,
      waveformMin: var_waveformMin,
      waveformMax: var_waveformMax,
    );
  }

  @protected
  MixerMeters sse_decode_mixer_meters(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_trackPeaksL = sse_decode_list_prim_f_32_strict(deserializer);
    var var_trackPeaksR = sse_decode_list_prim_f_32_strict(deserializer);
    var var_masterPeakL = sse_decode_f_32(deserializer);
    var var_masterPeakR = sse_decode_f_32(deserializer);
    return MixerMeters(
      trackPeaksL: var_trackPeaksL,
      trackPeaksR: var_trackPeaksR,
      masterPeakL: var_masterPeakL,
      masterPeakR: var_masterPeakR,
    );
  }

  @protected
  PlaybackStatus sse_decode_playback_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_positionSecs = sse_decode_f_64(deserializer);
    var var_playing = sse_decode_bool(deserializer);
    return PlaybackStatus(positionSecs: var_positionSecs, playing: var_playing);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mixer_meters_Sse(
    RustStreamSink<MixerMeters> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mixer_meters,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_playback_status_Sse(
    RustStreamSink<PlaybackStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_loaded_clip(LoadedClip self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.sampleRate, serializer);
    sse_encode_u_32(self.channels, serializer);
    sse_encode_u_64(self.frames, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
    sse_encode_list_prim_f_32_strict(self.waveformMin, serializer);
    sse_encode_list_prim_f_32_strict(self.waveformMax, serializer);
  }

  @protected
  void sse_encode_mixer_meters(MixerMeters self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.trackPeaksL, serializer);
    sse_encode_list_prim_f_32_strict(self.trackPeaksR, serializer);
    sse_encode_f_32(self.masterPeakL, serializer);
    sse_encode_f_32(self.masterPeakR, serializer);
  }

  @protected
  void sse_encode_playback_status(
    PlaybackStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.positionSecs, serializer);
    sse_encode_bool(self.playing, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
