// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/engine_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'project.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<MixerMeters> dco_decode_StreamSink_mixer_meters_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PlaybackStatus> dco_decode_StreamSink_playback_status_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ProjectFile dco_decode_box_autoadd_project_file(dynamic raw);

  @protected
  EqBandState dco_decode_eq_band_state(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<EqBandState> dco_decode_list_eq_band_state(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrackState> dco_decode_list_track_state(dynamic raw);

  @protected
  LoadedClip dco_decode_loaded_clip(dynamic raw);

  @protected
  MasterState dco_decode_master_state(dynamic raw);

  @protected
  MixerMeters dco_decode_mixer_meters(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlaybackStatus dco_decode_playback_status(dynamic raw);

  @protected
  ProjectFile dco_decode_project_file(dynamic raw);

  @protected
  TrackState dco_decode_track_state(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MixerMeters> sse_decode_StreamSink_mixer_meters_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PlaybackStatus> sse_decode_StreamSink_playback_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ProjectFile sse_decode_box_autoadd_project_file(SseDeserializer deserializer);

  @protected
  EqBandState sse_decode_eq_band_state(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<EqBandState> sse_decode_list_eq_band_state(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrackState> sse_decode_list_track_state(SseDeserializer deserializer);

  @protected
  LoadedClip sse_decode_loaded_clip(SseDeserializer deserializer);

  @protected
  MasterState sse_decode_master_state(SseDeserializer deserializer);

  @protected
  MixerMeters sse_decode_mixer_meters(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlaybackStatus sse_decode_playback_status(SseDeserializer deserializer);

  @protected
  ProjectFile sse_decode_project_file(SseDeserializer deserializer);

  @protected
  TrackState sse_decode_track_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mixer_meters_Sse(
    RustStreamSink<MixerMeters> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_playback_status_Sse(
    RustStreamSink<PlaybackStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_project_file(
    ProjectFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eq_band_state(EqBandState self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_eq_band_state(
    List<EqBandState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_state(
    List<TrackState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loaded_clip(LoadedClip self, SseSerializer serializer);

  @protected
  void sse_encode_master_state(MasterState self, SseSerializer serializer);

  @protected
  void sse_encode_mixer_meters(MixerMeters self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_status(
    PlaybackStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_file(ProjectFile self, SseSerializer serializer);

  @protected
  void sse_encode_track_state(TrackState self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
