// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One band of a 4-band EQ as it lives in the project file.
///
/// `kind` is the same small integer code [`crate::dsp::FilterKind::from_code`]
/// reads, so it round-trips through the existing bridge without a new mapping.
class EqBandState {
  /// Wire code matching [`FilterKind`] — 0 peak, 1 low-shelf, 2 high-shelf,
  /// 3 low-pass, 4 high-pass, 5 band-pass, 6 notch.
  final int kind;
  final double freqHz;
  final double q;
  final double gainDb;
  final bool enabled;

  const EqBandState({
    required this.kind,
    required this.freqHz,
    required this.q,
    required this.gainDb,
    required this.enabled,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      freqHz.hashCode ^
      q.hashCode ^
      gainDb.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqBandState &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          freqHz == other.freqHz &&
          q == other.q &&
          gainDb == other.gainDb &&
          enabled == other.enabled;
}

/// Master bus state. Same shape as a track minus identity and clip — the master
/// has its own EQ even though Milestone 4's UI doesn't expose it, so the
/// project file is forward-compatible with a future "master EQ" pane.
class MasterState {
  final double gainDb;
  final double pan;
  final List<EqBandState> eqBands;

  const MasterState({
    required this.gainDb,
    required this.pan,
    required this.eqBands,
  });

  @override
  int get hashCode => gainDb.hashCode ^ pan.hashCode ^ eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MasterState &&
          runtimeType == other.runtimeType &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          eqBands == other.eqBands;
}

/// One project's full state on disk and across the bridge.
///
/// `tracks` may have any length up to the engine's track-pool capacity
/// (`max_tracks()`); the Dart side enforces that bound. An empty `tracks` is
/// valid (a freshly-created project before the user adds anything).
class ProjectFile {
  /// On-disk schema version. See [`FORMAT_VERSION`].
  final int formatVersion;

  /// Human-readable project name. Used in the title bar; not constrained.
  final String name;

  /// One entry per user-visible track, in display order. Each entry's slot in
  /// the engine's strip pool is the track's index in this list — adding a
  /// track appends here, removing a track takes that index out and shifts the
  /// rest down so engine slots are contiguous from 0.
  final List<TrackState> tracks;

  /// The master bus chain.
  final MasterState master;

  const ProjectFile({
    required this.formatVersion,
    required this.name,
    required this.tracks,
    required this.master,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^
      name.hashCode ^
      tracks.hashCode ^
      master.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectFile &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          name == other.name &&
          tracks == other.tracks &&
          master == other.master;
}

/// One track's persistent state: identity, the WAV (if any) it loads, and the
/// parameters of its processing chain.
class TrackState {
  /// User-facing label ("Track 1", "Kick", …). The UI may auto-fill this on
  /// creation; serializing it lets a renamed track keep its name across loads.
  final String name;

  /// Absolute (or workspace-relative — Dart's choice) path to the WAV the
  /// track was last loaded with. `None` for an empty track. On load, missing
  /// files surface in the UI (the rest of the project still opens).
  final String? clipPath;

  /// Track fader gain in decibels.
  final double gainDb;

  /// Track pan, `[-1, 1]`.
  final double pan;

  /// EQ bands in order. The engine expects exactly four (matching
  /// `dsp::eq::NUM_BANDS`); a future schema version that loosens this would
  /// migrate here.
  final List<EqBandState> eqBands;

  const TrackState({
    required this.name,
    this.clipPath,
    required this.gainDb,
    required this.pan,
    required this.eqBands,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      clipPath.hashCode ^
      gainDb.hashCode ^
      pan.hashCode ^
      eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackState &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          clipPath == other.clipPath &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          eqBands == other.eqBands;
}
