// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One band of a 4-band EQ as it lives in the project file.
///
/// `kind` is the same small integer code [`crate::dsp::FilterKind::from_code`]
/// reads, so it round-trips through the existing bridge without a new mapping.
class EqBandState {
  /// Wire code matching [`FilterKind`] — 0 peak, 1 low-shelf, 2 high-shelf,
  /// 3 low-pass, 4 high-pass, 5 band-pass, 6 notch.
  final int kind;
  final double freqHz;
  final double q;
  final double gainDb;
  final bool enabled;

  const EqBandState({
    required this.kind,
    required this.freqHz,
    required this.q,
    required this.gainDb,
    required this.enabled,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      freqHz.hashCode ^
      q.hashCode ^
      gainDb.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqBandState &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          freqHz == other.freqHz &&
          q == other.q &&
          gainDb == other.gainDb &&
          enabled == other.enabled;
}

/// Master bus state. Same shape as a track minus identity and clips — the
/// master has its own EQ even though Milestone 4's UI doesn't expose it, so the
/// project file is forward-compatible with a future "master EQ" pane.
class MasterState {
  final double gainDb;
  final double pan;
  final List<EqBandState> eqBands;

  const MasterState({
    required this.gainDb,
    required this.pan,
    required this.eqBands,
  });

  @override
  int get hashCode => gainDb.hashCode ^ pan.hashCode ^ eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MasterState &&
          runtimeType == other.runtimeType &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          eqBands == other.eqBands;
}

/// One project's full state on disk and across the bridge.
///
/// `tracks` may have any length up to the engine's track-pool capacity
/// (`max_tracks()`); the Dart side enforces that bound. An empty `tracks` is
/// valid (a freshly-created project before the user adds anything).
class ProjectFile {
  /// On-disk schema version. See [`FORMAT_VERSION`].
  final int formatVersion;

  /// Human-readable project name. Used in the title bar; not constrained.
  final String name;

  /// Project tempo in BPM, used by the timeline UI to snap clip placements to
  /// bars/beats. The engine itself is tempo-agnostic — all timing on the
  /// audio thread is in device frames — so this is a UI/data concern.
  final double tempoBpm;

  /// One entry per user-visible track, in display order. Each entry's slot in
  /// the engine's strip pool is the track's index in this list — adding a
  /// track appends here, removing a track takes that index out and shifts the
  /// rest down so engine slots are contiguous from 0.
  final List<TrackState> tracks;

  /// The master bus chain.
  final MasterState master;

  const ProjectFile({
    required this.formatVersion,
    required this.name,
    required this.tempoBpm,
    required this.tracks,
    required this.master,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^
      name.hashCode ^
      tempoBpm.hashCode ^
      tracks.hashCode ^
      master.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectFile &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          name == other.name &&
          tempoBpm == other.tempoBpm &&
          tracks == other.tracks &&
          master == other.master;
}

/// One clip placed on a track's timeline. The shape mirrors
/// [`crate::sampler::TimelineClip`] minus the live `Arc<AudioClip>` — on save we
/// persist the source file path; on load the Dart side re-decodes each path
/// (best-effort) and pushes a `place_clip` call to put it back on the timeline.
class TrackClipState {
  /// Absolute (or workspace-relative — Dart's choice) path to the source WAV.
  /// On load, missing files surface in the UI as a broken-link clip; the rest
  /// of the project still opens.
  final String path;

  /// Position on the project timeline (device frames at the project's working
  /// sample rate) where this placement starts. Signed so a future "negative"
  /// placement is representable.
  final PlatformInt64 startFrame;

  /// Length on the timeline in device frames. `0` is the sentinel "use the
  /// source's full frame count" — keeps the JSON terse for the common case of
  /// dropping a whole WAV and not trimming it.
  final int lengthFrames;

  /// Where in the source to begin reading, in source-rate frames. Lets a
  /// trimmed-from-the-head clip persist without re-encoding the WAV.
  final int sourceOffsetFrames;

  const TrackClipState({
    required this.path,
    required this.startFrame,
    required this.lengthFrames,
    required this.sourceOffsetFrames,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      startFrame.hashCode ^
      lengthFrames.hashCode ^
      sourceOffsetFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackClipState &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          startFrame == other.startFrame &&
          lengthFrames == other.lengthFrames &&
          sourceOffsetFrames == other.sourceOffsetFrames;
}

/// One track's persistent state: identity, the clips placed on its timeline,
/// and the parameters of its processing chain.
class TrackState {
  /// User-facing label ("Track 1", "Kick", …). The UI may auto-fill this on
  /// creation; serializing it lets a renamed track keep its name across loads.
  final String name;

  /// Clips placed on this track's timeline. Order matches the engine's clip
  /// slot indices (`clips[i]` lands in sampler slot `i`), so the file's
  /// order is the source of truth for slot assignment. An empty list is a
  /// silent track. The list length is capped by the engine's
  /// `MAX_CLIPS_PER_TRACK`; the Dart side enforces that bound.
  final List<TrackClipState> clips;

  /// Track fader gain in decibels.
  final double gainDb;

  /// Track pan, `[-1, 1]`.
  final double pan;

  /// EQ bands in order. The engine expects exactly four (matching
  /// `dsp::eq::NUM_BANDS`); a future schema version that loosens this would
  /// migrate here.
  final List<EqBandState> eqBands;

  const TrackState({
    required this.name,
    required this.clips,
    required this.gainDb,
    required this.pan,
    required this.eqBands,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      clips.hashCode ^
      gainDb.hashCode ^
      pan.hashCode ^
      eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackState &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          clips == other.clips &&
          gainDb == other.gainDb &&
          pan == other.pan &&
          eqBands == other.eqBands;
}
