// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`

/// Start the audio engine and begin emitting a sine tone. Idempotent: calling it
/// while already running is a no-op. Returns an error (surfaced as a Dart
/// exception) if no audio device could be opened.
Future<void> startEngine() =>
    RustLib.instance.api.crateApiEngineApiStartEngine();

/// Stop the engine. Idempotent. Dropping the `Engine` tears down the stream and
/// joins the audio thread (RAII), so there's nothing else to clean up.
Future<void> stopEngine() => RustLib.instance.api.crateApiEngineApiStopEngine();

/// Set the oscillator frequency in Hz. Fire-and-forget and synchronous: it pushes
/// one command to the lock-free ring and returns immediately, so it's safe to
/// call on every slider tick. No-op if the engine isn't running.
///
/// `frb(sync)` makes this a plain synchronous call on the Dart side (returns
/// `void`, not `Future`) — there's no reason to await a ring-buffer push.
void setFrequency({required double hz}) =>
    RustLib.instance.api.crateApiEngineApiSetFrequency(hz: hz);

/// Whether the engine is currently running. Handy for the UI to reflect state.
bool isRunning() => RustLib.instance.api.crateApiEngineApiIsRunning();
