// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `with_engine`

/// Load and decode a WAV from disk, hand it to the audio engine, and return its
/// metadata + waveform summary. Starts the engine (opens the audio device) if it
/// isn't already running. The clip is loaded stopped at the start — call
/// [`play`] to hear it.
///
/// Async on the Dart side (it does real file I/O and decoding); throws a Dart
/// exception if the file can't be read or decoded.
Future<LoadedClip> loadWav({required String path}) =>
    RustLib.instance.api.crateApiEngineApiLoadWav(path: path);

/// Begin or resume playback. Fire-and-forget; no-op if no clip is loaded.
void play() => RustLib.instance.api.crateApiEngineApiPlay();

/// Pause playback, holding the current position. Fire-and-forget.
void pause() => RustLib.instance.api.crateApiEngineApiPause();

/// Stop playback and rewind to the start. Fire-and-forget.
void stop() => RustLib.instance.api.crateApiEngineApiStop();

/// Seek to `secs` from the clip start. Fire-and-forget; safe to call on every
/// scrub tick (the engine clamps to the clip bounds).
void seek({required double secs}) =>
    RustLib.instance.api.crateApiEngineApiSeek(secs: secs);

/// Turn looping on/off. Fire-and-forget; when on, playback wraps to the start
/// at the clip end instead of stopping.
void setLooping({required bool looping}) =>
    RustLib.instance.api.crateApiEngineApiSetLooping(looping: looping);

/// Set the channel-strip gain, in decibels (UI-natural). Fire-and-forget; safe
/// to call on every knob tick — the value is clamped and smoothed on the audio
/// thread, so a drag produces a click-free fade.
void setGainDb({required double db}) =>
    RustLib.instance.api.crateApiEngineApiSetGainDb(db: db);

/// Set the channel-strip gain as a raw linear multiplier (what the linear gain
/// fader drives). Fire-and-forget; clamped and smoothed on the audio thread.
void setGainLinear({required double linear}) =>
    RustLib.instance.api.crateApiEngineApiSetGainLinear(linear: linear);

/// Set the channel-strip pan, in `[-1, 1]` (−1 = hard left, 0 = center, +1 =
/// hard right). Fire-and-forget; clamped and smoothed on the audio thread.
void setPan({required double pan}) =>
    RustLib.instance.api.crateApiEngineApiSetPan(pan: pan);

/// Whether the audio engine is running (device open). Handy for the UI.
bool isRunning() => RustLib.instance.api.crateApiEngineApiIsRunning();

/// Stream of oscilloscope frames for the UI to draw. Each item is one
/// trigger-aligned window of mono samples (`Float32List` in Dart) — now the live
/// output of the WAV player. Subscribe once; the stream stays live for the app's
/// lifetime, emitting an empty frame while stopped and real audio while playing.
///
/// The audio callback only ever *pushes* samples into a lock-free ring; this
/// spawns a background pump that drains it ~60×/sec and hands frames to Dart.
/// Nothing here runs on, or blocks, the realtime thread.
Stream<Float32List> scopeStream() =>
    RustLib.instance.api.crateApiEngineApiScopeStream();

/// Stream of [`PlaybackStatus`] snapshots so the UI can animate the playhead and
/// reflect play/stop without polling. Also the convenient place to reclaim
/// retired clips: this pump runs on a control thread and locks the engine ~30×/s
/// anyway, so it drains the retirement ring each tick.
Stream<PlaybackStatus> playbackStatusStream() =>
    RustLib.instance.api.crateApiEngineApiPlaybackStatusStream();

/// Stream of post-fader [`MeterLevels`] (~60 Hz) — the first continuous
/// audio→UI level stream. The audio thread maintains a peak-hold-with-decay per
/// channel and publishes it to atomics each buffer; this pump reads those
/// atomics and hands them to Dart. Emits zeros while the engine is stopped.
///
/// As with the other pumps, nothing here runs on or blocks the audio thread —
/// reading an atomic is wait-free, and the lock taken is the control-side engine
/// mutex (never touched by the realtime callback).
Stream<MeterLevels> meterStream() =>
    RustLib.instance.api.crateApiEngineApiMeterStream();

/// What `load_wav` hands back to Dart: enough metadata to label the clip, plus a
/// precomputed min/max waveform summary for the display painter. Computing the
/// waveform once at load (not per frame) is the whole point — the UI just draws
/// these arrays. FRB mirrors this to a Dart class with `Float32List` fields.
class LoadedClip {
  /// File sample rate, Hz.
  final double sampleRate;

  /// Channel count (1 = mono, 2 = stereo).
  final int channels;

  /// Length in frames (samples per channel).
  final BigInt frames;

  /// Length in seconds.
  final double durationSecs;

  /// Per-column minimum of the mono-mixed signal, in `[-1, 1]`.
  final Float32List waveformMin;

  /// Per-column maximum of the mono-mixed signal, in `[-1, 1]`.
  final Float32List waveformMax;

  const LoadedClip({
    required this.sampleRate,
    required this.channels,
    required this.frames,
    required this.durationSecs,
    required this.waveformMin,
    required this.waveformMax,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      channels.hashCode ^
      frames.hashCode ^
      durationSecs.hashCode ^
      waveformMin.hashCode ^
      waveformMax.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadedClip &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          frames == other.frames &&
          durationSecs == other.durationSecs &&
          waveformMin == other.waveformMin &&
          waveformMax == other.waveformMax;
}

/// Post-fader peak levels per channel, linear (0..≈1, and can exceed 1 if the
/// gain is boosting). Streamed ~60×/sec — the first continuous audio→UI level
/// stream. The UI maps these to its own dB-scaled meter.
class MeterLevels {
  final double peakLeft;
  final double peakRight;

  const MeterLevels({required this.peakLeft, required this.peakRight});

  @override
  int get hashCode => peakLeft.hashCode ^ peakRight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeterLevels &&
          runtimeType == other.runtimeType &&
          peakLeft == other.peakLeft &&
          peakRight == other.peakRight;
}

/// A snapshot of transport state for the UI to animate the playhead and reflect
/// play/stop. Streamed ~30×/sec.
class PlaybackStatus {
  /// Current playhead position, seconds from the clip start.
  final double positionSecs;

  /// Whether playback is currently advancing.
  final bool playing;

  const PlaybackStatus({required this.positionSecs, required this.playing});

  @override
  int get hashCode => positionSecs.hashCode ^ playing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackStatus &&
          runtimeType == other.runtimeType &&
          positionSecs == other.positionSecs &&
          playing == other.playing;
}
